apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-pubsub-deployment
  labels:
    app: dotnet-pubsub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-pubsub
  template:
    metadata:
      labels:
        app: dotnet-pubsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dotnetapp"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: dotnet-pubsub
        image: jjatem/dapr-pubsub-test:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: dotnet-pubsub-service
  labels:
    app: dotnet-pubsub
spec:
  selector:
    app: dotnet-pubsub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dotnet-pubsub-ingress
spec:
  rules:
    - host: dotnet-pubsub.jjsoft.local
      http:
        paths:
          - backend:
              serviceName: dotnet-pubsub-service
              servicePort: 80
            path: /
