apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  metadata:
    - name: host
      value: "amqp://dapr:test001@rabbitmq-k8s.jjsoft.local:5672"
    - name: consumerID
      value: "daprConsumerID" # Required. Any unique ID. Example: "myConsumerID"
    - name: durable
      value: "true" # Optional. Default: "false"
    - name: deletedWhenUnused
      value: "false" # Optional. Default: "false"
    - name: autoAck
      value: "false" # Optional. Default: "false"
    - name: deliveryMode
      value: "0" # Optional. Default: "0". Values between 0 - 2.
    - name: requeueInFailure
      value: "false" # Optional. Default: "false".
